version: '3.8'
services:
  app:
    build: .
    env_file: .env.prod
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    env_file: .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: