services:
  app:
    build: .
    env_file: .env.prod
    networks:
      - nginx_net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    container_name: italian_api

  db:
    image: postgres:16-alpine
    env_file: .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  nginx_net:
    external: true