name: Deploy to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no deployer@${{ secrets.SERVER_IP }} "
            cd /opt/italian-me && \
            git pull && \
            docker compose -f docker-compose.prod.yml up -d --build
          "
